# Generated by Django 4.2.5 on 2023-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('open', models.BooleanField(default=False)),
            ],
        ),
    ]
