# Generated by Django 4.2.7 on 2023-11-30 07:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ddnUtilisateur', models.DateField(verbose_name='%d/%m/%Y')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('idDepartement', models.AutoField(primary_key=True, serialize=False)),
                ('nomDepartement', models.CharField(max_length=200, unique=True)),
                ('numeroDepartement', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('idHoraire', models.AutoField(primary_key=True, serialize=False)),
                ('listJour', models.CharField(max_length=300, null=True)),
                ('horaireOuverture', models.TimeField()),
                ('horaireFermeture', models.TimeField()),
                ('intervalHoraire', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('idLieu', models.AutoField(primary_key=True, serialize=False)),
                ('nomLieu', models.CharField(max_length=150, unique=True)),
                ('boolAccessibilite', models.BooleanField()),
                ('boolParking', models.BooleanField()),
                ('boolShopping', models.BooleanField()),
                ('boolRepas', models.BooleanField()),
                ('boolTable', models.BooleanField()),
                ('boolJaujeLieux', models.BooleanField()),
                ('nombreMaxVisiteur', models.IntegerField()),
                ('adresseLieu', models.CharField(max_length=250)),
                ('longitudeLieu', models.FloatField()),
                ('latitudeLieu', models.FloatField()),
                ('telLieu', models.IntegerField(max_length=10, null=True)),
                ('mailLieu', models.CharField(max_length=150, null=True)),
                ('webLieu', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nomRegion', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('idTarif', models.AutoField(primary_key=True, serialize=False)),
                ('payant', models.BooleanField()),
                ('reservation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeLieu',
            fields=[
                ('idTypeLieu', models.AutoField(primary_key=True, serialize=False)),
                ('nomTypeLieu', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('idVille', models.AutoField(primary_key=True, serialize=False)),
                ('nomVille', models.CharField(max_length=200, unique=True)),
                ('codePostal', models.IntegerField(max_length=5)),
                ('idDepartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departement')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lieu')),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('idParcours', models.AutoField(primary_key=True, serialize=False)),
                ('nomParcours', models.CharField(max_length=200)),
                ('typeParcours', models.CharField(max_length=200)),
                ('difficulteParcours', models.CharField(max_length=100)),
                ('distanceParcours', models.IntegerField()),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('idOeuvre', models.AutoField(primary_key=True, serialize=False)),
                ('nomOeuvre', models.CharField(max_length=200)),
                ('descriptionOeuvre', models.CharField(max_length=200)),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='LnkLieuHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('idHoraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.horaire')),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lieu')),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='idTarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarif'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='idTypeLieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typelieu'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='idVille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ville'),
        ),
        migrations.CreateModel(
            name='FavorisParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parcours')),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idEvenement', models.AutoField(primary_key=True, serialize=False)),
                ('nomEvenement', models.CharField(max_length=200, unique=True)),
                ('descriptionEvenement', models.CharField(max_length=200)),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEtape', models.IntegerField()),
                ('idLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lieu')),
                ('idParcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parcours')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
