# Generated by Django 4.2.7 on 2023-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='ddnUtilisateur',
            field=models.DateField(null=True, verbose_name='%d/%m/%Y'),
        ),
    ]
