# Generated by Django 4.2.5 on 2023-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_favorieparcours_favorisparcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='ddnUtilisateur',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='typeUtilisateur',
            field=models.BooleanField(),
        ),
    ]
